const $=id=>document.getElementById(id);

const panels={
menu:["MENU",'<div class="grid2">'+["vin","parts","doctor","repair","quote","clock","vision","manuals","gps","memory","scanner","settings"].map(x=>`<button class="action" onclick="openPanel('${x}')">${x.toUpperCase()}</button>`).join("")+'</div>'],
settings:["SETTINGS",`<button class="action" onclick="alert('Backend URL setup next')">BACKEND URL</button><button class="action" onclick="alert('Theme setup next')">THEME</button><button class="action" onclick="alert('Debug setup next')">DEBUG</button>`],
master:["MASTER SEARCH",`<textarea id="masterQ" class="field" rows="5" placeholder="VIN, part number, fault code, symptom, repair, quote note..."></textarea><button class="action" onclick="runMaster()">RUN SEARCH</button><div id="masterOut" class="output">Results show here.</div>`],
vin:["VIN LOOKUP",`<div class="grid2"><label>VIN<input id="vinIn" class="field" value="1XP4D49X8KD123456"></label><label>Engine<input id="engIn" class="field" value="Cummins X15"></label><label>ESN<input id="esnIn" class="field" value="79876562"></label><label>CPL<input id="cplIn" class="field" value="4342"></label></div><button class="action" onclick="saveTruck()">SAVE ACTIVE TRUCK</button><div id="vinOut" class="output">VIN system ready.</div>`],
parts:["OEM PARTS",`<textarea id="partQ" class="field" rows="4" placeholder="Part number or part name..."></textarea><button class="action" onclick="parts()">LOOKUP PART</button><button class="action" onclick="openCamera()">SCAN LABEL</button><div id="partsOut" class="output">Parts system ready.</div>`],
doctor:["DIESEL DOCTOR",`<textarea id="docQ" class="field" rows="4" placeholder="SPN/FMI, symptom, derate, regen, no-start..."></textarea><button class="action" onclick="doctor()">RUN DIAGNOSTIC</button><div id="docOut" class="output">Diagnostic system ready.</div>`],
repair:["REPAIR BRAIN",`<textarea id="repQ" class="field" rows="4" placeholder="Repair steps, tools, warnings..."></textarea><button class="action" onclick="repair()">BUILD REPAIR PLAN</button><div id="repOut" class="output">Repair Brain ready.</div>`],
quote:["SMART QUOTES",`<div class="grid2"><label>Labor Hours<input id="hrs" class="field" type="number" step="0.1"></label><label>Rate<input id="rate" class="field" type="number" value="135"></label><label>Call Out<input id="call" class="field" type="number" value="250"></label><label>Parts<input id="partsCost" class="field" type="number"></label></div><button class="action" onclick="quote()">BUILD QUOTE</button><div id="quoteOut" class="output">Quote ready.</div>`],
clock:["JOB CLOCK",`<div class="output" style="text-align:center"><b id="clockStatus" style="color:#ff7a00;font-size:28px">CLOCKED OUT</b><br><span id="clockTimer" style="font-size:54px;font-weight:900">0.00 hrs</span></div><div class="grid2"><button class="action" onclick="clockIn()">CLOCK IN</button><button class="action" onclick="clockOut()">CLOCK OUT</button></div><button class="action" onclick="resetClock()">RESET</button>`],
vision:["VISION / OCR",`<button class="action" onclick="openCamera()">OPEN CAMERA / PHOTO</button><div class="output">OCR shell ready. Backend vision API connects next.</div>`],
manuals:["SERVICE MANUALS",`<textarea class="field" rows="4" placeholder="Search manual/procedure..."></textarea><div class="output">Manual search shell ready.</div>`],
gps:["DOT / GPS",`<button class="action" onclick="gps()">DROP GPS PIN</button><div id="gpsOut" class="output">GPS ready.</div>`],
memory:["REPAIR MEMORY",`<textarea id="memQ" class="field" rows="4" placeholder="Save repair note..."></textarea><button class="action" onclick="memory()">SAVE MEMORY</button><div id="memOut" class="output">Memory ready.</div>`],
scanner:["SCANNER",`<div class="output">Bluetooth 9-pin / OBD2 / J1939 scanner module.\\n\\nStatus: READY TO CONNECT\\n\\nFuture connection:\\nws://localhost:8000/ws/j1939\\n\\nRoutes live DM1 faults, SPN/FMI, RPM, boost, coolant, oil temp into Diesel Doctor and Repair Brain.</div><button class="action" onclick="alert('Scanner WebSocket hook ready for backend')">CONNECT SCANNER</button>`],
gateway:["OEM GATEWAY",`<div class="output">OEM Gateway ready. Connects VIN, ESN, CPL, fault codes and OEM lookup systems.</div>`],
ai:["AI SYSTEM",`<div class="output">AI System online shell. Connects to FastAPI + Ollama backend.</div>`],
supabase:["SUPABASE SYNC",`<div class="output">Supabase sync shell ready. Stores repair memory, parts, VIN profiles and job records.</div>`],
offline:["OFFLINE MODE",`<div class="output">Offline mode ready. PWA cache installed for homepage and local shells.</div>`],
more:["MORE",`<div class="grid2"><button class="action" onclick="openPanel('scanner')">SCANNER</button><button class="action" onclick="openPanel('settings')">SETTINGS</button><button class="action" onclick="openPanel('memory')">MEMORY</button><button class="action" onclick="openPanel('gps')">GPS</button></div>`]
};

function openPanel(name){const p=panels[name]||panels.more;$("homeScreen").classList.remove("active");$("panelScreen").classList.add("active");$("panelTitle").textContent=p[0];$("panelBody").innerHTML=p[1];}
function goHome(){$("panelScreen").classList.remove("active");$("homeScreen").classList.add("active");}
function openCamera(){$("cameraInput").click();}
$("cameraInput").addEventListener("change",e=>{const f=e.target.files[0];if(f)alert("Photo loaded: "+f.name);});
function voiceShell(){alert("Voice shell ready. Backend connects next.");}
function runMaster(){const q=$("masterQ").value.trim();$("masterOut").textContent=q?`Searching Rolling Wrench AI:\\n${q}\\n\\nRoutes: VIN, Parts, Diesel Doctor, Repair Brain, Scanner, Quote Notes.`:"Enter a question first."}
function saveTruck(){let vin=$("vinIn").value||"NONE",eng=$("engIn").value||"UNKNOWN";$("vinOut").textContent=`Active truck saved.\\nVIN: ${vin}\\nEngine: ${eng.toUpperCase()}`;}
function parts(){const q=$("partQ").value.trim();$("partsOut").textContent=q?`OEM parts lookup shell:\\n${q}\\n\\nNext: Supabase/parts database.`:"Enter part number/name."}
function doctor(){const q=$("docQ").value.trim();$("docOut").textContent=q?`Diesel Doctor shell:\\n${q}\\n\\nNext: FastAPI/Ollama/Neo4j diagnostics.`:"Enter fault/symptom."}
function repair(){const q=$("repQ").value.trim();$("repOut").textContent=q?`Repair Brain shell:\\n${q}\\n\\nNext: repair memory + known fixes.`:"Enter repair question."}
function quote(){let h=+$("hrs").value||0,r=+$("rate").value||0,c=+$("call").value||0,p=+$("partsCost").value||0,t=h*r+c+p;$("quoteOut").textContent=`ROLLING WRENCH QUOTE\\nLabor: ${h.toFixed(2)} x $${r.toFixed(2)} = $${(h*r).toFixed(2)}\\nCall Out: $${c.toFixed(2)}\\nParts: $${p.toFixed(2)}\\nTOTAL: $${t.toFixed(2)}`}
let st=null,timer=null;function clockIn(){st=Date.now();$("clockStatus").textContent="CLOCKED IN";clearInterval(timer);timer=setInterval(updateClock,1000);updateClock()}function updateClock(){if(!st)return;$("clockTimer").textContent=((Date.now()-st)/3600000).toFixed(2)+" hrs"}function clockOut(){updateClock();$("clockStatus").textContent="CLOCKED OUT";clearInterval(timer)}function resetClock(){st=null;clearInterval(timer);$("clockStatus").textContent="CLOCKED OUT";$("clockTimer").textContent="0.00 hrs"}
function gps(){if(!navigator.geolocation){$("gpsOut").textContent="GPS not supported.";return;}$("gpsOut").textContent="Getting GPS...";navigator.geolocation.getCurrentPosition(p=>$("gpsOut").textContent=`GPS Pin:\\n${p.coords.latitude.toFixed(6)}, ${p.coords.longitude.toFixed(6)}`,()=>$("gpsOut").textContent="GPS denied/unavailable.")}
function memory(){localStorage.setItem("rwRepairMemory",$("memQ").value);$("memOut").textContent="Repair memory saved locally."}
if("serviceWorker" in navigator){navigator.serviceWorker.register("service-worker.js").catch(()=>{});}
