const $ = id => document.getElementById(id);
const $$ = q => Array.from(document.querySelectorAll(q));
const money = n => Number(n||0).toLocaleString(undefined,{style:'currency',currency:'USD'});
const store = {get:(k,d)=>{try{return JSON.parse(localStorage.getItem('rwai_'+k)) ?? d}catch{return d}},set:(k,v)=>localStorage.setItem('rwai_'+k,JSON.stringify(v))};
let clockTimer;
function settings(){return store.get('settings',{shopName:'Rolling Wrench Diesel LLC',shopPhone:'260-502-6222',shopWeb:'www.rollingwrenchdiesel.com',defaultRate:135,defaultService:250})}
function setScreen(id){$$('.screen').forEach(s=>s.classList.toggle('active',s.id===id));$$('[data-screen],.nav,.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.screen===id));$('rail')?.classList.remove('open');window.scrollTo({top:0,behavior:'smooth'});}
function bindNav(){document.addEventListener('click',e=>{const btn=e.target.closest('button');if(!btn)return;if(btn.dataset.screen)setScreen(btn.dataset.screen);if(btn.classList.contains('back'))setScreen('home');if(btn.dataset.action==='newInvoice'){clearInvoice(false);setScreen('invoices')}if(btn.dataset.clear){btn.dataset.clear.split(',').forEach(id=>{if($(id))$(id).value?$(id).value='':$(id).textContent='';});} });$('menuBtn')?.addEventListener('click',()=>$('rail').classList.toggle('open'));}
function truck(){return store.get('truck',{})}
function truckTitle(t=truck()){return [t.year,t.make,t.model].filter(Boolean).join(' ')||'No truck selected'}
function truckContext(){const t=truck();return `ACTIVE TRUCK\n${truckTitle(t)}\nVIN: ${t.vin||'NONE'}\nEngine: ${t.engine||'Unknown'}\nESN: ${t.esn||'None'} | CPL/EPA: ${t.cpl||'None'}`}
function refreshTruck(){const t=truck();['vin','year','make','model','engine','odo','esn','cpl'].forEach(id=>{if($(id))$(id).value=t[id]||''});$('homeTruckTitle').textContent=truckTitle(t);$('homeVin').textContent=t.vin||'NONE';$('homeEngine').textContent=t.engine||'Unknown';$('homeOdo').textContent=t.odo||'Not set';if($('invTruck'))$('invTruck').value=truckTitle(t);if($('invVin'))$('invVin').value=t.vin||'';}
function saveTruck(){const t={vin:$('vin').value.trim().toUpperCase(),year:$('year').value.trim(),make:$('make').value.trim(),model:$('model').value.trim(),engine:$('engine').value.trim(),odo:$('odo').value.trim(),esn:$('esn').value.trim(),cpl:$('cpl').value.trim()};store.set('truck',t);refreshTruck();$('truckOut').textContent=`TRUCK SAVED\n\n${truckContext()}`;}
function clearTruck(){localStorage.removeItem('rwai_truck');refreshTruck();$('truckOut').textContent='Active truck cleared.';}
function decodeVinDemo(){const vin=$('vin').value.trim().toUpperCase();if(vin==='3HSDZTZR5KN536244'){$('year').value='2019';$('make').value='International';$('model').value='LT / RH Series';$('engine').value='International A26';$('truckOut').textContent='Demo decoded: 2019 International LT/RH with A26 context. Save to make active.'}else{$('truckOut').textContent='Offline demo decode. Live NHTSA vPIC can be wired to this button in the backend pass.'}}
function getClock(){return store.get('clock',{running:false,startedAt:null,elapsedMs:0,rate:135})}
function currentElapsed(c=getClock()){return c.elapsedMs+(c.running&&c.startedAt?Date.now()-c.startedAt:0)}
function fmt(ms){const s=Math.floor(ms/1000),h=Math.floor(s/3600),m=Math.floor((s%3600)/60),ss=s%60;return [h,m,ss].map(x=>String(x).padStart(2,'0')).join(':')}
function renderClock(){const c=getClock();const rate=Number($('clockRate')?.value||c.rate||settings().defaultRate);const total=currentElapsed(c)/3600000*rate;['topTime','clockTime'].forEach(id=>{if($(id))$(id).textContent=fmt(currentElapsed(c))});['topMoney','clockMoney'].forEach(id=>{if($(id))$(id).textContent=money(total)});$('clockStatus').textContent=c.running?'● ON THE CLOCK':'● ON STANDBY';$('clockLabel').innerHTML=c.running?'Click to<br><b>Clock Out</b>':'Click to<br><b>Clock In</b>';}
function setClock(c){store.set('clock',c);renderClock()}
function startClock(){const c=getClock();c.rate=Number($('clockRate')?.value)||settings().defaultRate;if(!c.running){c.running=true;c.startedAt=Date.now()}setClock(c);$('clockOut').textContent='Clock running. Hours and money are rolling live.'}
function pauseClock(){const c=getClock();if(c.running){c.elapsedMs=currentElapsed(c);c.running=false;c.startedAt=null}setClock(c);$('clockOut').textContent='Clock paused. Total is saved.'}
function resetClock(){setClock({running:false,startedAt:null,elapsedMs:0,rate:Number($('clockRate')?.value)||settings().defaultRate});$('clockOut').textContent='Clock reset.'}
function toggleClock(){getClock().running?pauseClock():startClock()}
function sendClockInvoice(){const c=getClock();$('hours').value=(currentElapsed(c)/3600000).toFixed(2);$('rate').value=Number($('clockRate')?.value)||settings().defaultRate;setScreen('invoices');calcInvoice()}
function faultTree(){const q=$('faultInput').value.trim();if(!q){$('faultOut').textContent='Enter a fault code or symptom first.';return} $('faultOut').textContent=`ROLLING WRENCH AI — FAULT DOCTOR\n\n${truckContext()}\n\nCONCERN\n${q}\n\nPRIORITY DIAGNOSTIC TREE\n1. Confirm active/inactive status, freeze-frame, derate level, and customer complaint.\n2. Inspect power, ground, connectors, pin drag, corrosion, rubbed harness and recent repair areas before replacing parts.\n3. Compare live data key-on, idle, loaded and during regen/requested test.\n4. If aftertreatment related, check exhaust leaks, temperature sensor plausibility, DEF quality, dosing, pressure tubes, soot load and regen history.\n5. Document verified failed test, not just a code.\n\nLIKELY BUCKETS\n• Harness / connector fault\n• Sensor biased or failed\n• Air/exhaust leak changing readings\n• Restriction, dosing, or regen issue\n• Calibration or learned-value issue\n\nNEXT MOVE\nRun the pinpoint tests, save results to Repair HUD, then build invoice from confirmed repair.`}
function partLookup(){const q=$('partInput').value.trim();if(!q){$('partOut').textContent='Enter a part number or description first.';return} $('partOut').textContent=`ROLLING WRENCH AI — OEM PARTS LOOKUP\n\n${truckContext()}\n\nSEARCH\n${q}\n\nNOTES\n${$('partNotes').value||'No extra notes entered.'}\n\nGUARDRAILS\n• Do not guess exact OEM part number without VIN/ESN/CPL or label/casting confirmation.\n• Return OEM number, supersession, cross-references, kit parts, seals/gaskets/hardware, torque notes and supplier options.\n• If ambiguous, ask for VIN, ESN, CPL, tag photo or casting number.\n\nDEMO RESULT\nLookup package is ready to attach to invoice/work order. Backend live catalog search can plug into this same output panel.`}
function buildRepair(){const txt=`COMPLAINT:\n${$('complaint').value||'Not entered.'}\n\nCAUSE:\n${$('cause').value||'Pending diagnostic confirmation.'}\n\nCORRECTION:\n${$('correction').value||'Not entered.'}`;$('repairOut').textContent=txt;return txt}
function sendFaultRepair(){$('complaint').value=$('faultInput').value;$('cause').value='Pending pinpoint test confirmation.';$('correction').value=$('faultOut').textContent;setScreen('repair');buildRepair()}
function sendPartInvoice(){$('work').value=($('work').value+'\n\nPART LOOKUP NOTE:\n'+$('partOut').textContent).trim();setScreen('invoices');calcInvoice()}
function sendRepairInvoice(){$('work').value=buildRepair();setScreen('invoices');calcInvoice()}
function calcInvoice(){const s=settings();const hours=Number($('hours').value)||0,rate=Number($('rate').value)||0,svc=Number($('service').value)||0,parts=Number($('partsCost').value)||0,taxPct=Number($('tax').value)||0,cardPct=Number($('card').value)||0;const labor=hours*rate,sub=labor+svc+parts,tax=sub*taxPct/100,card=(sub+tax)*cardPct/100,total=sub+tax+card;const txt=`${s.shopName}\n${s.shopPhone} • ${s.shopWeb}\n\nCUSTOMER: ${$('cust').value||'Customer'}\nTRUCK: ${$('invTruck').value||'Not set'}\nVIN: ${$('invVin').value||'Not set'}\n\nWORK PERFORMED:\n${$('work').value||'No work notes entered.'}\n\nLabor: ${hours.toFixed(2)} hr × ${money(rate)} = ${money(labor)}\nService Call: ${money(svc)}\nParts: ${money(parts)}\nSubtotal: ${money(sub)}\nTax: ${money(tax)}\nCard Fee: ${money(card)}\n\nTOTAL: ${money(total)}`;$('invoiceOut').textContent=txt;return {txt,total}}
async function copyInvoice(){const {txt}=calcInvoice();try{await navigator.clipboard.writeText(txt);$('invoiceOut').textContent=txt+'\n\nCopied to clipboard.'}catch{$('invoiceOut').textContent=txt+'\n\nCopy blocked by browser. Select and copy manually.'}}
function clearInvoice(show=true){['cust','work'].forEach(id=>$(id).value='');$('hours').value=0;$('rate').value=settings().defaultRate;$('service').value=settings().defaultService;$('partsCost').value=0;$('tax').value=0;$('card').value=0;refreshTruck();if(show)calcInvoice()}
function saveInvoice(){const inv=store.get('invoices',[]);const out=calcInvoice();inv.unshift({id:'INV-'+String(20000+inv.length+1),date:new Date().toLocaleDateString(),amount:out.total,status:'SAVED'});store.set('invoices',inv.slice(0,20));renderLists();$('invoiceOut').textContent=out.txt+'\n\nSaved locally.'}
function runAi(){const q=$('askAi').value.trim();if(!q){$('aiOut').textContent='Ask something first.';return}const l=q.toLowerCase();if(l.includes('spn')||l.includes('fmi')||l.includes('fault')||l.includes('derate')){$('faultInput').value=q;faultTree();setScreen('faults');return}if(l.includes('part')||l.includes('seal')||l.includes('pump')||l.includes('valve')||l.includes('filter')){$('partInput').value=q;partLookup();setScreen('parts');return}if(l.includes('quote')||l.includes('invoice')||l.includes('hour')){$('work').value=q;setScreen('invoices');calcInvoice();return}$('aiOut').textContent=`ROLLING WRENCH AI ROUTER\n\n${truckContext()}\n\nQUESTION\n${q}\n\nBest route: Fault Doctor for symptoms/codes, Parts Lookup for OEM/cross-ref, Time Clock for labor, Invoice for quote, Repair HUD for C/C/C notes.`}
function saveSettings(){const s={shopName:$('shopName').value,shopPhone:$('shopPhone').value,shopWeb:$('shopWeb').value,defaultRate:Number($('defaultRate').value)||135,defaultService:Number($('defaultService').value)||250};store.set('settings',s);$('rate').value=s.defaultRate;$('service').value=s.defaultService;$('clockRate').value=s.defaultRate;$('settingsOut').textContent='Settings saved.'}
function loadSettings(){const s=settings();Object.entries(s).forEach(([k,v])=>{if($(k))$(k).value=v});if($('rate'))$('rate').value=s.defaultRate;if($('service'))$('service').value=s.defaultService;if($('clockRate'))$('clockRate').value=s.defaultRate}
function renderLists(){const wos=store.get('workorders',[{id:'WO-10045',job:'DPF Cleaning',date:'05/18/2026',status:'IN PROGRESS'},{id:'WO-10044',job:'EGR Valve Replacement',date:'05/17/2026',status:'COMPLETE'},{id:'WO-10043',job:'Coolant Temp Sensor',date:'05/17/2026',status:'COMPLETE'},{id:'WO-10042',job:'Air Leak Inspection',date:'05/16/2026',status:'COMPLETE'}]);const inv=store.get('invoices',[{id:'INV-20031',date:'05/18/2026',amount:1842.50,status:'PAID'},{id:'INV-20030',date:'05/17/2026',amount:2450,status:'PAID'},{id:'QUOTE-30012',date:'05/17/2026',amount:3125.75,status:'SENT'},{id:'INV-20029',date:'05/16/2026',amount:975,status:'PAID'}]);$('homeWorkOrders').innerHTML=wos.slice(0,4).map(x=>`<div class="row"><b>${x.id}</b><span>${x.job}</span><span>${x.date}</span><em class="pill ${x.status.includes('PROGRESS')?'progress':'complete'}">${x.status}</em></div>`).join('');$('workOrderList').innerHTML=wos.map(x=>`<div class="row"><b>${x.id}</b><span>${x.job}</span><span>${x.date}</span><em class="pill ${x.status.includes('PROGRESS')?'progress':'complete'}">${x.status}</em></div>`).join('');$('homeInvoices').innerHTML=inv.slice(0,4).map(x=>`<div class="row"><b>${x.id}</b><span>${money(x.amount)}</span><span>${x.date}</span><em class="pill ${x.status==='SENT'?'sent':'paid'}">${x.status}</em></div>`).join('');$('historyList').innerHTML=[...wos,...inv].map(x=>`<div class="row"><b>${x.id}</b><span>${x.job||money(x.amount)}</span><span>${x.date}</span><em class="pill">${x.status}</em></div>`).join('')}
function newWO(){const wos=store.get('workorders',[]);wos.unshift({id:'WO-'+(10046+wos.length),job:'New Field Repair',date:new Date().toLocaleDateString(),status:'IN PROGRESS'});store.set('workorders',wos);renderLists()}
function boot(){bindNav();loadSettings();refreshTruck();renderLists();renderClock();clockTimer=setInterval(renderClock,1000);$('saveTruck').onclick=saveTruck;$('clearTruck').onclick=clearTruck;$('decodeVin').onclick=decodeVinDemo;$('quickClock').onclick=toggleClock;$('startClock').onclick=startClock;$('pauseClock').onclick=pauseClock;$('resetClock').onclick=resetClock;$('sendClockInvoice').onclick=sendClockInvoice;$('runFault').onclick=faultTree;$('sendFaultRepair').onclick=sendFaultRepair;$('runPart').onclick=partLookup;$('sendPartInvoice').onclick=sendPartInvoice;$('buildRepair').onclick=buildRepair;$('sendRepairInvoice').onclick=sendRepairInvoice;$('calcInvoice').onclick=calcInvoice;$('copyInvoice').onclick=copyInvoice;$('clearInvoice').onclick=clearInvoice;$('saveInvoice').onclick=saveInvoice;$('runAi').onclick=runAi;$('saveSettings').onclick=saveSettings;$('defaultSettings').onclick=()=>{localStorage.removeItem('rwai_settings');loadSettings();};$('newWO').onclick=newWO;$('clockRate').addEventListener('input',()=>{const c=getClock();c.rate=Number($('clockRate').value)||settings().defaultRate;store.set('clock',c);renderClock()});calcInvoice()}
document.addEventListener('DOMContentLoaded',boot);
